language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: COMPOSER_VERSION=1.0.*
    - php: 5.6
      env: COMPOSER_VERSION=1.1.*
    - php: 5.6
      env: COMPOSER_VERSION=dev-master
    # Incompatibility message test check. Must be kept
    - php: 5.6
      env: COMPOSER_VERSION=1.0.0-beta1
  allow_failures:
    - php: nightly
    - env: COMPOSER_VERSION=1.1.*
    - env: COMPOSER_VERSION=dev-master

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi;
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - composer global require phpunit/phpunit:@stable satooshi/php-coveralls:@stable codeclimate/php-test-reporter:@stable --no-update
  - if [ "$COMPOSER_VERSION" != "" ]; then composer require "composer/composer:${COMPOSER_VERSION}" --no-update; fi;

install:
  - composer global update --prefer-dist --no-interaction
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

before_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "zend_extension=xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;

script: phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_script:
  - coveralls -v
  - test-reporter
